---
name: arrows
description: Replace ASCII arrows by LaTeX arrows
license: MIT
author: Jakob Voß <jakob.voss@gbv.de>
version: 0.1.0 # should match a git tag in source repository
repository: repository

requires:
  - name: pandoc
    version: 1.12
  - name: perl
    version: 5.14    
    libraries: # Perl libraries => install via cpanm from CPAN
      - name: Pandoc::Elements
        version: 0.16
filter: arrows  # which file to copy to ~/.pandoc/filters
...
